<?php
/** DPDPA AMP - FAQs. @package SucceedLEARN\AMP */
if ( ! defined( 'ABSPATH' ) ) { exit; }
$faq_items = array(
array('question'=>__('Is DPDPA training mandatory for employees in India?','succeedlearn-amp'),'answer'=>__('The DPDP Act, 2023 does not name a specific course. It does require organisations to take reasonable security safeguards to protect personal data, and trained employees are one of the most practical ways to show those safeguards are in place. Penalties for certain failures, such as not taking reasonable safeguards against a breach, can reach ₹250 crore.','succeedlearn-amp')),
array('question'=>__('What does DPDPA training for employees cover?','succeedlearn-amp'),'answer'=>__('Key DPDPA terms, what counts as personal data, lawful grounds and consent, privacy by design, handling data from collection to deletion, Data Principal rights, grievances and breach reporting, followed by a short final assessment.','succeedlearn-amp')),
array('question'=>__('How long is the DPDPA compliance training course?','succeedlearn-amp'),'answer'=>__('About 25 minutes. It is self-paced, so employees can finish in one sitting or across a few short sessions.','succeedlearn-amp')),
array('question'=>__('Can we run the DPDPA course on our own LMS as SCORM?','succeedlearn-amp'),'answer'=>__('Yes. Upload it to your existing LMS as a SCORM package, or run it on the SucceedLEARN LMS with ready-made reports and reminder emails.','succeedlearn-amp')),
array('question'=>__('How do we track completion and prove the training happened?','succeedlearn-amp'),'answer'=>__('Learners work through interactive checks, then a final assessment drawn from a larger question bank, with a score of 80% needed to pass. A certificate of completion is issued automatically on passing. On our LMS you get completion reports by department; with SCORM, completion and score are recorded in your own LMS.','succeedlearn-amp')),
array('question'=>__('Can the course carry our own branding?','succeedlearn-amp'),'answer'=>__('Yes. The first 25 customers get up to 10 minutes of course content customised free, including their own policies, examples and branding. This includes your logo and policy in the course, a branded learning portal, and dedicated support throughout your journey, whenever you need help.','succeedlearn-amp')),
array('question'=>__('Does the course cover the DPDP Rules, 2025?','succeedlearn-amp'),'answer'=>__('The course is built around the DPDP Act, 2023. The DPDP Rules, 2025, notified in November 2025, add procedural detail such as timelines and notice formats. Your internal processes can be reflected through customisation.','succeedlearn-amp')),
array('question'=>__('What happens in the 20-minute demo?','succeedlearn-amp'),'answer'=>__('We walk you through the course, the interactive activities, the certificate and the admin reports, and answer questions about rollout for your headcount. No preparation is needed.','succeedlearn-amp')),
);
?>
<section class="sl-section sl-section--alt sl-dpdpa-faq" id="faq" aria-labelledby="sl-dpdpa-faq-title"><div class="sl-wrap"><header class="sl-dpdpa-section-head"><h2 id="sl-dpdpa-faq-title" class="sl-h2"><?php esc_html_e( 'DPDPA training ', 'succeedlearn-amp' ); ?><span><?php esc_html_e( 'FAQs', 'succeedlearn-amp' ); ?></span></h2><p class="sl-lead"><?php esc_html_e( 'Still have a question? Your 20-minute demo is the fastest way to get answers for your organisation.', 'succeedlearn-amp' ); ?></p></header><?php succeedlearn_amp_render_faq_accordion( $faq_items ); ?></div></section>
